In [4]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [19]:
zero_array = np.zeros(shape = (5,3,6)) #matriz, linhas , colunas 
# pode ser np.ones
print(zero_array)

print(zero_array.shape)
print(zero_array.size)
print(zero_array.ndim)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
(5, 3, 6)
90
3


In [11]:
# Dá uma sequência de números:
zero_dez = np.arange(15)
print(zero_dez)
pula_dois = np.arange(3,15,2)
print(pula_dois)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  5  7  9 11 13]


In [18]:
# valores espaçados igualmente entre si 
array_linear = np.linspace(0, 100 , num = 20, endpoint = False, retstep = True)
print(array_linear)

(array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75., 80., 85., 90., 95.]), 5.0)


In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.concatenate((a,b))
d = np.concatenate((b,a))

print(c)
print(d)

[1 2 3 4 5 6]
[4 5 6 1 2 3]


In [22]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(a)
print('------------')
print(a[a>11])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------
[12]


In [24]:
a = np.array([1,2,3])

print(a.max())
print(a.min())
print(a.mean())
print(a.sum())

3
1
2.0
6


In [27]:
from numpy.random import default_rng
rng = default_rng()
aleatorio = rng.integers(10, size=(2,3))
print(rng)
print(aleatorio)

Generator(PCG64)
[[0 1 4]
 [3 9 8]]


In [31]:
a = np.array([1,2,3,4,5,6,7,8])
print("Esse é o array 'a':",a)
print("Esse é o tipo de 'a':", type(a))
print('-----------------------------------------')
lista_a = [1,2,3,4,5,6,7,8]
print("Essa é a 'lista_a':", lista_a)
print("Esse é o tipo de 'lista_a':", type(lista_a))

#arrays não permitem tipos de dados distintos:
a = np.array([1,'Daniel',2,3,4,5,6,7,8])
print(a)
print(type(a[0]))

#já as listas sim:
lista_a = [1,'Daniel',2,3,4,5,6,7,8]
print(a)
print(type(lista_a[0]))

Esse é o array 'a': [1 2 3 4 5 6 7 8]
Esse é o tipo de 'a': <class 'numpy.ndarray'>
-----------------------------------------
Essa é a 'lista_a': [1, 2, 3, 4, 5, 6, 7, 8]
Esse é o tipo de 'lista_a': <class 'list'>
['1' 'Daniel' '2' '3' '4' '5' '6' '7' '8']
<class 'numpy.str_'>
['1' 'Daniel' '2' '3' '4' '5' '6' '7' '8']
<class 'int'>
